// AUTOMATIC GENERATION : DO NOT MODIFY !
// Date : 2024-05-21T14:24:49.801Z
// List of files in ./src/modules/classic/blueprints

module.exports = {
  'c-cave-locust': require('./creatures/monsters/c-cave-locust.json'),
  'c-centaur': require('./creatures/monsters/c-centaur.json'),
  'c-ghast': require('./creatures/monsters/c-ghast.json'),
  'c-ghost': require('./creatures/monsters/c-ghost.json'),
  'c-ghoul': require('./creatures/monsters/c-ghoul.json'),
  'c-spectre': require('./creatures/monsters/c-spectre.json'),
  'c-vampire': require('./creatures/monsters/c-vampire.json'),
  'c-zombie': require('./creatures/monsters/c-zombie.json'),
  'ammo-arrow': require('./items/ammunitions/ammo-arrow.json'),
  'ammo-quarrel': require('./items/ammunitions/ammo-quarrel.json'),
  'arm-chain-mail': require('./items/armors/arm-chain-mail.json'),
  'arm-clothing': require('./items/armors/arm-clothing.json'),
  'arm-leather': require('./items/armors/arm-leather.json'),
  'arm-plate': require('./items/armors/arm-plate.json'),
  'shd-small': require('./items/shields/shd-small.json'),
  'wpn-battleaxe': require('./items/weapons/wpn-battleaxe.json'),
  'wpn-club': require('./items/weapons/wpn-club.json'),
  'wpn-dagger-sharp': require('./items/weapons/wpn-dagger-sharp.json'),
  'wpn-dagger': require('./items/weapons/wpn-dagger.json'),
  'wpn-greataxe': require('./items/weapons/wpn-greataxe.json'),
  'wpn-greatsword': require('./items/weapons/wpn-greatsword.json'),
  'wpn-handaxe': require('./items/weapons/wpn-handaxe.json'),
  'wpn-heavy-crossbow': require('./items/weapons/wpn-heavy-crossbow.json'),
  'wpn-light-crossbow': require('./items/weapons/wpn-light-crossbow.json'),
  'wpn-longbow': require('./items/weapons/wpn-longbow.json'),
  'wpn-longsword': require('./items/weapons/wpn-longsword.json'),
  'wpn-mace': require('./items/weapons/wpn-mace.json'),
  'wpn-maul': require('./items/weapons/wpn-maul.json'),
  'wpn-quarterstaff': require('./items/weapons/wpn-quarterstaff.json'),
  'wpn-shortbow': require('./items/weapons/wpn-shortbow.json'),
  'wpn-shortsword': require('./items/weapons/wpn-shortsword.json'),
  'wpn-silver-dagger': require('./items/weapons/wpn-silver-dagger.json'),
  'wpn-spear': require('./items/weapons/wpn-spear.json'),
  'wpn-warhammer': require('./items/weapons/wpn-warhammer.json')
}
