// AUTOMATIC GENERATION : DO NOT MODIFY !
// Date : 2024-05-06T15:12:55.381Z
// List of files in ./src/store/getters

module.exports = {
  'getAbilities': require('./getAbilities.js'),
  'getAbilityModifiers': require('./getAbilityModifiers.js'),
  'getActions': require('./getActions.js'),
  'getArmorClass': require('./getArmorClass.js'),
  'getAttackBonus': require('./getAttackBonus.js'),
  'getAttackRollCriticalValue': require('./getAttackRollCriticalValue.js'),
  'getAttackRollFumbleValue': require('./getAttackRollFumbleValue.js'),
  'getCapabilities': require('./getCapabilities.js'),
  'getClassTypeData': require('./getClassTypeData.js'),
  'getConditionSet': require('./getConditionSet.js'),
  'getDamageMitigation': require('./getDamageMitigation.js'),
  'getDefensiveEquipmentProperties': require('./getDefensiveEquipmentProperties.js'),
  'getEffectRegistry': require('./getEffectRegistry.js'),
  'getEffectSet': require('./getEffectSet.js'),
  'getEffects': require('./getEffects.js'),
  'getEquipment': require('./getEquipment.js'),
  'getHitPoints': require('./getHitPoints.js'),
  'getLevel': require('./getLevel.js'),
  'getMaxHitPoints': require('./getMaxHitPoints.js'),
  'getMeleeActions': require('./getMeleeActions.js'),
  'getMonsterData': require('./getMonsterData.js'),
  'getOffensiveEquipment': require('./getOffensiveEquipment.js'),
  'getOffensiveEquipmentProperties': require('./getOffensiveEquipmentProperties.js'),
  'getOffensiveSlot': require('./getOffensiveSlot.js'),
  'getProperties': require('./getProperties.js'),
  'getRangedActions': require('./getRangedActions.js'),
  'getRecentDamages': require('./getRecentDamages.js'),
  'getSavingThrowFailureValue': require('./getSavingThrowFailureValue.js'),
  'getSavingThrowSucessValue': require('./getSavingThrowSucessValue.js'),
  'getSelectedAction': require('./getSelectedAction.js'),
  'getSelectedWeapon': require('./getSelectedWeapon.js'),
  'getSpecie': require('./getSpecie.js'),
  'getSpeed': require('./getSpeed.js'),
  'isDead': require('./isDead.js'),
  'isRangedWeaponLoaded': require('./isRangedWeaponLoaded.js'),
  'isSelectedWeaponUsable': require('./isSelectedWeaponUsable.js'),
  'isWieldingTwoHandedWeapon': require('./isWieldingTwoHandedWeapon.js')
}
