// AUTOMATIC GENERATION : DO NOT MODIFY !
// Date : 2024-04-09T06:51:05.013Z
// List of files in ./src/effects

module.exports = {
  "EFFECT_ABILITY_MODIFIER": "EFFECT_ABILITY_MODIFIER",
  "EFFECT_ARMOR_CLASS_MODIFIER": "EFFECT_ARMOR_CLASS_MODIFIER",
  "EFFECT_ATTACK_MODIFIER": "EFFECT_ATTACK_MODIFIER",
  "EFFECT_DAMAGE_MODIFIER": "EFFECT_DAMAGE_MODIFIER",
  "EFFECT_HEAL": "EFFECT_HEAL",
  "EFFECT_SPEED_MODIFIER": "EFFECT_SPEED_MODIFIER"
}
