// AUTOMATIC GENERATION : DO NOT MODIFY !
// Date : 2024-03-15T16:48:08.484Z
// List of files in ./src/effects

module.exports = {
  "EFFECT_DAMAGE_MODIFIER": "EFFECT_DAMAGE_MODIFIER",
  "EFFECT_HEAL": "EFFECT_HEAL"
}
